---
- name: "upgrade undercloud"
  hosts: undercloud
  become_user: stack


  roles:
#    - rhosp-check
#    - undercloud-nic-update
#    - undercloud-leapp-update
    - undercloud-prerequisite-director
    - undercloud-update-director
