  - name: Check the pre-upgrade requirements
    shell: |
        source ~/stackrc
        openstack tripleo validator run --group pre-upgrade --python-interpreter /usr/libexec/platform-python -i inventory.yaml
    ignore_errors: true
    register: results_validate
  - debug:
      var: results_validate.stdout_lines

# Put here ip controller-0
  - name: Disable fencing
    shell: |
        source ~/stackrc
        ssh -o StrictHostKeyChecking=no heat-admin@10.165.3.153 "sudo pcs property set stonith-enabled=false"
