  - name: " Create inventory / tripleo-ansible-inventory --static-yaml-inventory ~/inventory.yaml "
    shell: |
        source ~/stackrc
        tripleo-ansible-inventory --static-yaml-inventory ~/inventory.yaml
    register: results_validate
  - debug:
      var: results_validate.stdout_lines

  - name: " Check the pre-upgrade requirements / openstack tripleo validator run --group pre-upgrade --python-interpreter /usr/libexec/platform-python -i inventory.yaml "
    shell: |
        source ~/stackrc
        openstack tripleo validator run --group pre-upgrade --python-interpreter /usr/libexec/platform-python -i inventory.yaml
    ignore_errors: true
    register: results_validate
  - debug:
      var: results_validate.stdout_lines

  - name: "Disable fencing / sudo pcs property set stonith-enabled=false"
    shell: |
        source ~/stackrc
        ssh -o StrictHostKeyChecking=no heat-admin@10.165.3.164 "sudo pcs property set stonith-enabled=false"
        ssh -o StrictHostKeyChecking=no heat-admin@10.165.3.168 "sudo pcs property set stonith-enabled=false"
        ssh -o StrictHostKeyChecking=no heat-admin@10.165.3.147 "sudo pcs property set stonith-enabled=false"

  - name: "Enable subscription / sudo subscription-manager register"
    shell: |
        source ~/stackrc
        ssh -o StrictHostKeyChecking=no heat-admin@10.165.3.168 "sudo subscription-manager register --username envops --password 'Unix_11!' --auto-attach"
    register: results_validate
  - debug:
      var: results_validate.stdout_lines
