  - name: " Install dependency / sudo yum install jq leapp-upgrade -y "
    shell: |
       source ~/stackrc
       ssh -o StrictHostKeyChecking=no heat-admin@10.165.3.170 "sudo yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y"
       ssh -o StrictHostKeyChecking=no heat-admin@10.165.3.170 "sudo yum install jq -y"
       ssh -o StrictHostKeyChecking=no heat-admin@10.165.3.170 "sudo subscription-manager repos --enable rhel-7-server-rpms"
       ssh -o StrictHostKeyChecking=no heat-admin@10.165.3.170 "sudo subscription-manager repos --enable rhel-7-server-extras-rpms"
       ssh -o StrictHostKeyChecking=no heat-admin@10.165.3.170 "sudo yum update -y"
       ssh -o StrictHostKeyChecking=no heat-admin@10.165.3.170 "sudo yum install leapp-upgrade -y"
       ssh -o StrictHostKeyChecking=no heat-admin@10.165.3.170 "sudo yum remove epel-release -y"
 
  - name: " Creating an upgrades environment file / touch templates/upgrades-environment.yaml "
    shell: |
        source ~/stackrc
        touch templates/upgrades-environment.yaml
  - debug:
      var: results_validate.stdout_lines

  - name: " Enable repo --enablerepo rhel-8-for-x86_64-baseos-eus-rpms --enablerepo rhel-8-for-x86_64-appstream-eus-rpms "
    ansible.builtin.blockinfile:
      path: /home/stack/templates/upgrades-environment.yaml
      block: |
          parameter_defaults:
            UpgradeLeappCommandOptions: " --enablerepo rhel-8-for-x86_64-baseos-eus-rpms --enablerepo rhel-8-for-x86_64-appstream-eus-rpms --enablerepo rhel-8-for-x86_64-highavailability-eus-rpms --enablerepo ansible-2.9-for-rhel-8-x86_64-rpms --enablerepo fast-datapath-for-rhel-8-x86_64-rpms "

  - name: Creating extra templates
    shell: |
        source ~/stackrc
        touch templates/extra_template.yaml
        touch templates/rhsm.yaml
  - debug:
     var: results_validate.stdout_lines

  - name: Red Hat Subscription Manager (RHSM) composable service
    ansible.builtin.blockinfile:
      path: /home/stack/templates/extra_template.yaml
      block: |
          resource_registry:
            OS::TripleO::Services::Rhsm: /usr/share/openstack-tripleo-heat-templates/deployment/rhsm/rhsm-baremetal-ansible.yaml
          
  - name: Applying the rhsm composable service
    ansible.builtin.blockinfile:
      path: /home/stack/templates/rhsm.yaml
      block: |
        resource_registry:
          OS::TripleO::Services::Rhsm: /usr/share/openstack-tripleo-heat-templates/deployment/rhsm/rhsm-baremetal-ansible.yaml
        parameter_defaults:
          RhsmVars:
            rhsm_repos:
              - rhel-8-for-x86_64-baseos-eus-rpms
              - rhel-8-for-x86_64-appstream-eus-rpms
              - rhel-8-for-x86_64-highavailability-eus-rpms
              - ansible-2.9-for-rhel-8-x86_64-rpms
              - openstack-16.2-for-rhel-8-x86_64-rpms
              - fast-datapath-for-rhel-8-x86_64-rpms
            rhsm_username: "envops"
            rhsm_password: "Unix_11!"
            autosubscribe: "true"
            rhsm_org_id: "16300313"
            rhsm_method: "portal"
            rhsm_release: 8.4


#  - name: Insert docker credentionals 
#    ansible.builtin.blockinfile:
#      path: /home/stack/templates/upgrades-environment.yaml
#      block: |
#          parameter_defaults:
#            UpgradeLeappDevelSkip: "LEAPP_UNSUPPORTED=1 LEAPP_DEVEL_TARGET_RELEASE=8.4"
#            LeappInitCommand: |
#              for module in pata_acpi floppy; do sudo sed -i "/^${module}$/d" /usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/kernel/checkkerneldrivers/files/removed_drivers.txt; done
#              sudo rm -f /usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/persistentnetnamesdisable/actor.py
#              sudo yum -y remove mariadb-server* || true
#            UpgradeInitCommand: "sudo dnf config-manager --save --setopt exclude=''"
 
 
  - name: " Copying the Leapp data on the overcloud nodes / tripleo-ansible-inventory --static-yaml-inventory ~/inventory.yaml "
    shell: |
        source ~/stackrc
        tripleo-ansible-inventory --static-yaml-inventory ~/inventory.yaml
              
  - name: Replace tripleo-admin
    shell: |
       source ~/stackrc
       sed  -i 's/tripleo-admin/heat-admin/g' ~/inventory.yaml
  
  - name: " Run ansible playbook / ansible -i ~/inventory.yaml --become -m synchronize "
    shell: |
       source ~/stackrc  
       ansible -i ~/inventory.yaml --become -m synchronize -a "src=/etc/leapp/files dest=/etc/leapp/" overcloud

  - name: " Using predictable NIC names for overcloud nodes / ansible-playbook -i ~/inventory.yaml playbook-nics.yaml "
    shell: |
        source ~/stackrc      
        export ANSIBLE_HOST_KEY_CHECKING=False
        ansible-playbook -i ~/inventory.yaml playbook-nics.yaml
