  - name: Creating an upgrades environment file
    shell: |
        source ~/stackrc
        touch templates/upgrades-environment.yaml

  - name: Enable repo
    ansible.builtin.blockinfile:
      path: /home/stack/templates/upgrades-environment.yaml
      block: |
          parameter_defaults:
            UpgradeLeappCommandOptions: UpgradeLeappCommandOptions: " --enablerepo rhel-8-for-x86_64-baseos-eus-rpms --enablerepo rhel-8-for-x86_64-appstream-eus-rpms --enablerepo rhel-8-for-x86_64-highavailability-eus-rpms --enablerepo ansible-2.9-for-rhel-8-x86_64-rpms --enablerepo fast-datapath-for-rhel-8-x86_64-rpms "

  - name: Creating extra templates
    shell: |
        source ~/stackrc
        touch templates/extra_template.yaml
        touch templates/rhsm.yaml

  - name: Red Hat Subscription Manager (RHSM) composable service
    ansible.builtin.blockinfile:
      path: /home/stack/templates/extra_template.yaml
      block: |
          resource_registry:
            OS::TripleO::Services::Rhsm: /usr/share/openstack-tripleo-heat-templates/deployment/rhsm/rhsm-baremetal-ansible.yaml
          
  - name: Applying the rhsm composable service
    ansible.builtin.blockinfile:
      path: /home/stack/templates/rhsm.yaml
      block: |
        resource_registry:
          OS::TripleO::Services::Rhsm: /usr/share/openstack-tripleo-heat-templates/deployment/rhsm/rhsm-baremetal-ansible.yaml
        parameter_defaults:
          RhsmVars:
            rhsm_repos:
              - rhel-8-for-x86_64-baseos-eus-rpms
              - rhel-8-for-x86_64-appstream-eus-rpms
              - rhel-8-for-x86_64-highavailability-eus-rpms
              - ansible-2.9-for-rhel-8-x86_64-rpms
              - openstack-16.2-for-rhel-8-x86_64-rpms
              - fast-datapath-for-rhel-8-x86_64-rpms
            rhsm_username: "envops"
            rhsm_password: "Unix_11!"
            rhsm_org_id: "16300313"
            rhsm_method: "portal"
            rhsm_release: 8.4


#  - name: Insert docker credentionals 
#    ansible.builtin.blockinfile:
#      path: /home/stack/templates/upgrades-environment.yaml
#      block: |
#          parameter_defaults:
#            UpgradeLeappDevelSkip: "LEAPP_UNSUPPORTED=1 LEAPP_DEVEL_TARGET_RELEASE=8.4"
#            LeappInitCommand: |
#              for module in pata_acpi floppy; do sudo sed -i "/^${module}$/d" /usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/kernel/checkkerneldrivers/files/removed_drivers.txt; done
#              sudo rm -f /usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/persistentnetnamesdisable/actor.py
#              sudo yum -y remove mariadb-server* || true
#            UpgradeInitCommand: "sudo dnf config-manager --save --setopt exclude=''"
 
 
#  - name: Copying the Leapp data on the overcloud nodes
#    shell: |
#        source ~/stackrc
#        tripleo-ansible-inventory --static-yaml-inventory ~/inventory.yaml
              
#  - name: Replace tripleo-admin
#    shell: |
#       source ~/stackrc
#       sed  -i 's/tripleo-admin/heat-admin/g' ~/inventory.yaml
  
#  - name: Run ansible playbook
#    shell: |
#       source ~/stackrc  
#       ansible -i ~/inventory.yaml --become -m synchronize -a "src=/etc/leapp/files dest=/etc/leapp/" overcloud
        
  - name: Using predictable NIC names for overcloud nodes
    shell: |
        source ~/stackrc      
        export ANSIBLE_HOST_KEY_CHECKING=False
        ansible-playbook -i ~/inventory.yaml playbook-nics.yaml
