  - name: Create script
    shell: |
        source ~/stackrc      
        touch update-nic-templates.sh
  
  - name: Updating network interface templates
    ansible.builtin.blockinfile:
      path: /home/stack/update-nic-templates.sh
      block: |
          #!/bin/bash
          STACK_NAME="overcloud"
          ROLES_DATA="/usr/share/openstack-tripleo-heat-templates/roles_data.yaml"
          NETWORK_DATA="/usr/share/openstack-tripleo-heat-templates/network_data.yaml"
          NIC_CONFIG_LINES=$(openstack stack environment show $STACK_NAME | grep "::Net::SoftwareConfig" | sed -E 's/ *OS::TripleO::// ; s/::Net::SoftwareConfig:// ; s/ http.*user-files/ /')
          echo "$NIC_CONFIG_LINES" | while read LINE; do
              ROLE=$(echo "$LINE" | awk '{print $1;}')
              NIC_CONFIG=$(echo "$LINE" | awk '{print $2;}')

              if [ -f "$NIC_CONFIG" ]; then
                  echo "Updating template for $ROLE role."
                  python3 /usr/share/openstack-tripleo-heat-templates/tools/merge-new-params-nic-config-script.py \
                      --tht-dir /usr/share/openstack-tripleo-heat-templates \
                      --roles-data $ROLES_DATA \
                      --network-data $NETWORK_DATA \
                      --role-name "$ROLE" \
                      --discard-comments yes \
                      --template "$NIC_CONFIG"
              else
                   echo "No NIC template detected for $ROLE role. Skipping $ROLE role."
              fi
           done
 
   - name: Add executable permissions to the script
     shell: |
         source ~/stackrc      
         chmod +x update-nic-templates.sh
 
   - name: Run the script
     shell: |
          source ~/stackrc  
          ./update-nic-templates.sh
